// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: ricart_agrawala.proto

package ricart_agrawala

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RicartAgrawala_RequestAccess_FullMethodName = "/ricart_agrawala.RicartAgrawala/RequestAccess"
	RicartAgrawala_ReplyAccess_FullMethodName   = "/ricart_agrawala.RicartAgrawala/ReplyAccess"
)

// RicartAgrawalaClient is the client API for RicartAgrawala service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RicartAgrawalaClient interface {
	RequestAccess(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Ack, error)
	ReplyAccess(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Ack, error)
}

type ricartAgrawalaClient struct {
	cc grpc.ClientConnInterface
}

func NewRicartAgrawalaClient(cc grpc.ClientConnInterface) RicartAgrawalaClient {
	return &ricartAgrawalaClient{cc}
}

func (c *ricartAgrawalaClient) RequestAccess(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, RicartAgrawala_RequestAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ricartAgrawalaClient) ReplyAccess(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, RicartAgrawala_ReplyAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RicartAgrawalaServer is the server API for RicartAgrawala service.
// All implementations must embed UnimplementedRicartAgrawalaServer
// for forward compatibility.
type RicartAgrawalaServer interface {
	RequestAccess(context.Context, *Message) (*Ack, error)
	ReplyAccess(context.Context, *Message) (*Ack, error)
	mustEmbedUnimplementedRicartAgrawalaServer()
}

// UnimplementedRicartAgrawalaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRicartAgrawalaServer struct{}

func (UnimplementedRicartAgrawalaServer) RequestAccess(context.Context, *Message) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestAccess not implemented")
}
func (UnimplementedRicartAgrawalaServer) ReplyAccess(context.Context, *Message) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplyAccess not implemented")
}
func (UnimplementedRicartAgrawalaServer) mustEmbedUnimplementedRicartAgrawalaServer() {}
func (UnimplementedRicartAgrawalaServer) testEmbeddedByValue()                        {}

// UnsafeRicartAgrawalaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RicartAgrawalaServer will
// result in compilation errors.
type UnsafeRicartAgrawalaServer interface {
	mustEmbedUnimplementedRicartAgrawalaServer()
}

func RegisterRicartAgrawalaServer(s grpc.ServiceRegistrar, srv RicartAgrawalaServer) {
	// If the following call pancis, it indicates UnimplementedRicartAgrawalaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RicartAgrawala_ServiceDesc, srv)
}

func _RicartAgrawala_RequestAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RicartAgrawalaServer).RequestAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RicartAgrawala_RequestAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RicartAgrawalaServer).RequestAccess(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _RicartAgrawala_ReplyAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RicartAgrawalaServer).ReplyAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RicartAgrawala_ReplyAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RicartAgrawalaServer).ReplyAccess(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// RicartAgrawala_ServiceDesc is the grpc.ServiceDesc for RicartAgrawala service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RicartAgrawala_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ricart_agrawala.RicartAgrawala",
	HandlerType: (*RicartAgrawalaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestAccess",
			Handler:    _RicartAgrawala_RequestAccess_Handler,
		},
		{
			MethodName: "ReplyAccess",
			Handler:    _RicartAgrawala_ReplyAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ricart_agrawala.proto",
}
