// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.3
// source: ricart_agrawala.proto

package ricart_agrawala

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	ProcessId     int32                  `protobuf:"varint,2,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_ricart_agrawala_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_ricart_agrawala_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_ricart_agrawala_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Message) GetProcessId() int32 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_ricart_agrawala_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_ricart_agrawala_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_ricart_agrawala_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_ricart_agrawala_proto protoreflect.FileDescriptor

const file_ricart_agrawala_proto_rawDesc = "" +
	"\n" +
	"\x15ricart_agrawala.proto\x12\x0fricart_agrawala\"Z\n" +
	"\aMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x1d\n" +
	"\n" +
	"process_id\x18\x02 \x01(\x05R\tprocessId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x1f\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x90\x01\n" +
	"\x0eRicartAgrawala\x12?\n" +
	"\rRequestAccess\x12\x18.ricart_agrawala.Message\x1a\x14.ricart_agrawala.Ack\x12=\n" +
	"\vReplyAccess\x12\x18.ricart_agrawala.Message\x1a\x14.ricart_agrawala.AckB\x14Z\x12./;ricart_agrawalab\x06proto3"

var (
	file_ricart_agrawala_proto_rawDescOnce sync.Once
	file_ricart_agrawala_proto_rawDescData []byte
)

func file_ricart_agrawala_proto_rawDescGZIP() []byte {
	file_ricart_agrawala_proto_rawDescOnce.Do(func() {
		file_ricart_agrawala_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ricart_agrawala_proto_rawDesc), len(file_ricart_agrawala_proto_rawDesc)))
	})
	return file_ricart_agrawala_proto_rawDescData
}

var file_ricart_agrawala_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ricart_agrawala_proto_goTypes = []any{
	(*Message)(nil), // 0: ricart_agrawala.Message
	(*Ack)(nil),     // 1: ricart_agrawala.Ack
}
var file_ricart_agrawala_proto_depIdxs = []int32{
	0, // 0: ricart_agrawala.RicartAgrawala.RequestAccess:input_type -> ricart_agrawala.Message
	0, // 1: ricart_agrawala.RicartAgrawala.ReplyAccess:input_type -> ricart_agrawala.Message
	1, // 2: ricart_agrawala.RicartAgrawala.RequestAccess:output_type -> ricart_agrawala.Ack
	1, // 3: ricart_agrawala.RicartAgrawala.ReplyAccess:output_type -> ricart_agrawala.Ack
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ricart_agrawala_proto_init() }
func file_ricart_agrawala_proto_init() {
	if File_ricart_agrawala_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ricart_agrawala_proto_rawDesc), len(file_ricart_agrawala_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ricart_agrawala_proto_goTypes,
		DependencyIndexes: file_ricart_agrawala_proto_depIdxs,
		MessageInfos:      file_ricart_agrawala_proto_msgTypes,
	}.Build()
	File_ricart_agrawala_proto = out.File
	file_ricart_agrawala_proto_goTypes = nil
	file_ricart_agrawala_proto_depIdxs = nil
}
